# Use Cloth Config mod for the descriptions.
---
contributorCosmetic: ''
cosmeticScreenKeybind: false
globalTooltip: false
noMicrosoftTelemetry: true
qol:
  suppressExperimentalSettingsWarning: true
  titleScreenNoFade: false
  hideDataComponentsTooltip: false
  loadingOverlayNoFade: false
debug:
  showTranslatedTagsByDefault: false
  printDataComponentsWhenCopy: true
  tagsTooltip: false
  debugTooltipMsg: false
  tagsTooltipAppendKeybindHint: true
  F3CopyInInventory: true
  tagsPerPage: 6
