["Mekanism Lasers Config"]
	#Cooldown of the ore generator (in seconds)
	# Default: 4
	# Range: > 0
	oreGeneratorCooldown = 1
	#Energy cost of fabricating ore/ores
	# Default: 16000000
	# Range: 0 ~ 2147483647
	oreGeneratorFabricationCost = 50000
	#How much ores do you get from one cycle
	# Default: 1
	# Range: > 1
	oreGeneratorNumberOfOres = 1
	#List of ores to blacklist from generation
	blacklistedOres = [
  "create:deepslate_zinc_ore",
  "ftbmaterials:aluminum_deepslate_ore",
  "ftbmaterials:aluminum_end_ore",
  "ftbmaterials:aluminum_nether_ore",
  "ftbmaterials:antimony_deepslate_ore",
  "ftbmaterials:antimony_end_ore",
  "ftbmaterials:antimony_nether_ore",
  "ftbmaterials:apatite_deepslate_ore",
  "ftbmaterials:apatite_end_ore",
  "ftbmaterials:apatite_nether_ore",
  "ftbmaterials:apatite_stone_ore",
  "ftbmaterials:bauxite_deepslate_ore",
  "ftbmaterials:bauxite_end_ore",
  "ftbmaterials:bauxite_nether_ore",
  "ftbmaterials:cinnabar_deepslate_ore",
  "ftbmaterials:cinnabar_end_ore",
  "ftbmaterials:cinnabar_nether_ore",
  "ftbmaterials:cinnabar_stone_ore",
  "ftbmaterials:coal_end_ore",
  "ftbmaterials:coal_nether_ore",
  "ftbmaterials:copper_end_ore",
  "ftbmaterials:copper_nether_ore",
  "ftbmaterials:diamond_end_ore",
  "ftbmaterials:diamond_nether_ore",
  "ftbmaterials:dimensional_shard_deepslate_ore",
  "ftbmaterials:dimensional_shard_end_ore",
  "ftbmaterials:dimensional_shard_nether_ore",
  "ftbmaterials:dimensional_shard_stone_ore",
  "ftbmaterials:emerald_end_ore",
  "ftbmaterials:emerald_nether_ore",
  "ftbmaterials:fluorite_deepslate_ore",
  "ftbmaterials:fluorite_end_ore",
  "ftbmaterials:gold_end_ore",
  "ftbmaterials:gold_nether_ore",
  "ftbmaterials:iridium_deepslate_ore",
  "ftbmaterials:iridium_end_ore",
  "ftbmaterials:iridium_nether_ore",
  "ftbmaterials:iron_end_ore",
  "ftbmaterials:iron_nether_ore",
  "ftbmaterials:lapis_lazuli_end_ore",
  "ftbmaterials:lapis_lazuli_nether_ore",
  "ftbmaterials:lead_deepslate_ore",
  "ftbmaterials:lead_end_ore",
  "ftbmaterials:monazite_deepslate_ore",
  "ftbmaterials:monazite_end_ore",
  "ftbmaterials:monazite_nether_ore",
  "ftbmaterials:nickel_deepslate_ore",
  "ftbmaterials:nickel_end_ore",
  "ftbmaterials:nickel_nether_ore",
  "ftbmaterials:niter_deepslate_ore",
  "ftbmaterials:niter_end_ore",
  "ftbmaterials:niter_nether_ore",
  "ftbmaterials:osmium_deepslate_ore",
  "ftbmaterials:platinum_deepslate_ore",
  "ftbmaterials:platinum_end_ore",
  "ftbmaterials:platinum_nether_ore",
  "ftbmaterials:quartz_deepslate_ore",
  "ftbmaterials:quartz_end_ore",
  "ftbmaterials:quartz_stone_ore",
  "ftbmaterials:redstone_end_ore",
  "ftbmaterials:redstone_nether_ore",
  "ftbmaterials:resonating_ore_deepslate_ore",
  "ftbmaterials:resonating_ore_end_ore",
  "ftbmaterials:resonating_ore_nether_ore",
  "ftbmaterials:resonating_ore_stone_ore",
  "ftbmaterials:ruby_deepslate_ore",
  "ftbmaterials:ruby_end_ore",
  "ftbmaterials:ruby_nether_ore",
  "ftbmaterials:ruby_stone_ore",
  "ftbmaterials:salt_deepslate_ore",
  "ftbmaterials:salt_end_ore",
  "ftbmaterials:salt_nether_ore",
  "ftbmaterials:sapphire_deepslate_ore",
  "ftbmaterials:sapphire_end_ore",
  "ftbmaterials:sapphire_nether_ore",
  "ftbmaterials:sapphire_stone_ore",
  "ftbmaterials:silver_deepslate_ore",
  "ftbmaterials:silver_end_ore",
  "ftbmaterials:silver_nether_ore",
  "ftbmaterials:sulfur_deepslate_ore",
  "ftbmaterials:sulfur_end_ore",
  "ftbmaterials:sulfur_nether_ore",
  "ftbmaterials:sulfur_stone_ore",
  "ftbmaterials:tin_deepslate_ore",
  "ftbmaterials:tin_end_ore",
  "ftbmaterials:tin_nether_ore",
  "ftbmaterials:titanium_deepslate_ore",
  "ftbmaterials:titanium_end_ore",
  "ftbmaterials:titanium_nether_ore",
  "ftbmaterials:titanium_stone_ore",
  "ftbmaterials:tungsten_deepslate_ore",
  "ftbmaterials:tungsten_end_ore",
  "ftbmaterials:tungsten_nether_ore",
  "ftbmaterials:tungsten_stone_ore",
  "ftbmaterials:uranium_deepslate_ore",
  "ftbmaterials:uranium_end_ore",
  "ftbmaterials:uranium_nether_ore",
  "ftbmaterials:zinc_deepslate_ore",
  "ftbmaterials:zinc_end_ore",
  "ftbmaterials:zinc_nether_ore",
  "ftbmaterials:zinc_stone_ore",
  "irons_spellbooks:deepslate_mithril_ore",
  "justdirethings:raw_blazegold_ore",
  "justdirethings:raw_celestigem_ore",
  "justdirethings:raw_coal_t1_ore",
  "justdirethings:raw_coal_t2_ore",
  "justdirethings:raw_coal_t3_ore",
  "justdirethings:raw_coal_t4_ore",
  "justdirethings:raw_eclipsealloy_ore",
  "justdirethings:raw_ferricore_ore",
  "malum:blazing_quartz_ore",
  "malum:brilliant_deepslate",
  "malum:deepslate_quartz_ore",
  "malum:deepslate_soulstone_ore",
  "malum:natural_quartz_ore",
  "mekanism:deepslate_fluorite_ore",
  "mekanism:deepslate_lead_ore",
  "mekanism:deepslate_osmium_ore",
  "mekanism:deepslate_tin_ore",
  "mekanism:deepslate_uranium_ore",
  "mekanism:fluorite_ore",
  "mekanism:lead_ore",
  "mekanism:osmium_ore",
  "mekanism:raw_uranium",
  "mekanism:tin_ore",
  "mekanism:uranium_ore",
  "minecraft:deepslate_coal_ore",
  "minecraft:deepslate_copper_ore",
  "minecraft:deepslate_diamond_ore",
  "minecraft:deepslate_emerald_ore",
  "minecraft:deepslate_gold_ore",
  "minecraft:deepslate_iron_ore",
  "minecraft:deepslate_lapis_ore",
  "minecraft:deepslate_redstone_ore",
  "minecraft:nether_gold_ore",
  "minecraft:nether_quartz_ore",
  "modern_industrialization:antimony_ore",
  "modern_industrialization:bauxite_ore",
  "modern_industrialization:deepslate_antimony_ore",
  "modern_industrialization:deepslate_bauxite_ore",
  "modern_industrialization:deepslate_iridium_ore",
  "modern_industrialization:deepslate_lead_ore",
  "modern_industrialization:deepslate_lignite_coal_ore",
  "modern_industrialization:deepslate_monazite_ore",
  "modern_industrialization:deepslate_nickel_ore",
  "modern_industrialization:deepslate_salt_ore",
  "modern_industrialization:deepslate_tin_ore",
  "modern_industrialization:deepslate_tungsten_ore",
  "modern_industrialization:deepslate_uranium_ore",
  "modern_industrialization:iridium_ore",
  "modern_industrialization:lignite_coal_ore",
  "modern_industrialization:lead_ore",
  "modern_industrialization:monazite_ore",
  "modern_industrialization:nickel_ore",
  "modern_industrialization:platinum_ore",
  "modern_industrialization:quartz_ore",
  "modern_industrialization:raw_nickel",
  "modern_industrialization:raw_platinum",
  "modern_industrialization:salt_ore",
  "modern_industrialization:tin_ore",
  "modern_industrialization:titanium_ore",
  "modern_industrialization:tungsten_ore",
  "modern_industrialization:uranium_ore",
  "mysticalagriculture:deepslate_inferium_ore",
  "mysticalagriculture:deepslate_prosperity_ore",
  "mysticalagradditions:end_inferium_ore",
  "mysticalagradditions:end_prosperity_ore",
  "mysticalagradditions:nether_inferium_ore",
  "mysticalagradditions:nether_prosperity_ore",
  "occultism:iesnium_ore",
  "occultism:silver_ore",
  "occultism:silver_ore_deepslate",
  "oritech:deepslate_nickel_ore",
  "oritech:deepslate_platinum_ore",
  "oritech:deepslate_uranium_ore",
  "oritech:endstone_platinum_ore",
  "oritech:nickel_ore",
  "petrock:deepslate_stoneium_ore",
  "petrock:stoneium_ore",
  "powah:deepslate_uraninite_ore",
  "powah:deepslate_uraninite_ore_dense",
  "powah:deepslate_uraninite_ore_poor",
  "powah:uraninite_ore_dense",
  "powah:uraninite_ore_poor",
  "replication:deepslate_replica_ore",
  "rftoolsbase:dimensionalshard_end",
  "rftoolsbase:dimensionalshard_nether",
  "rftoolsbase:dimensionalshard_overworld",
  "roots:deepslate_silver_ore",
  "roots:granite_quartz_ore",
  "roots:silver_ore",
  "silentgear:deepslate_bort_ore",
  "xycraft_world:aluminum_ore_deepslate",
  "xycraft_world:aluminum_ore_kivi",
  "xycraft_world:aluminum_ore_stone",
  "xycraft_world:xychorium_ore_deepslate_blue",
  "xycraft_world:xychorium_ore_deepslate_dark",
  "xycraft_world:xychorium_ore_deepslate_green",
  "xycraft_world:xychorium_ore_deepslate_light",
  "xycraft_world:xychorium_ore_deepslate_red",
  "xycraft_world:xychorium_ore_kivi_blue",
  "xycraft_world:xychorium_ore_kivi_dark",
  "xycraft_world:xychorium_ore_kivi_green",
  "xycraft_world:xychorium_ore_kivi_light",
  "xycraft_world:xychorium_ore_kivi_red",
  "xycraft_world:xychorium_ore_stone_blue",
  "xycraft_world:xychorium_ore_stone_dark",
  "xycraft_world:xychorium_ore_stone_green",
  "xycraft_world:xychorium_ore_stone_light",
  "xycraft_world:xychorium_ore_stone_red",
  "silentgear:blackstone_crimson_iron_ore"
]

