#magnetism-related configuration
[magnetism]
	#whether or not experience orbs should be teleported when using magnetism
	move_experience_orbs = true

#Reputation-related configurations
[reputation_config]
	#whether or not the Untrue Pacifist advancement is granted or utilized
	pacifist_disabled = false

#Runic Shears configuration options
[runic_shears]
	#the X half value for the size of the Runic Shears aoe bounding box
	# Default: 3
	# Range: > 1
	aoe_bounding_box_x = 3
	#the Y half value for the size of the Runic Shears aoe bounding box
	# Default: 3
	# Range: > 1
	aoe_bounding_box_y = 3
	#the Z half value for the size of the Runic Shears aoe bounding box
	# Default: 3
	# Range: > 1
	aoe_bounding_box_z = 3

#Options for Pyres and Rituals
[pyre]
	#the X half value for the size of the Pyre aoe bounding box
	# Default: 10
	# Range: > 1
	pyre_bounds_x = 10
	#the Y half value for the size of the Pyre aoe bounding box
	# Default: 10
	# Range: > 1
	pyre_bounds_y = 10
	#the Z half value for the size of the Pyre aoe bounding box
	# Default: 10
	# Range: > 1
	pyre_bounds_z = 10

#Options for sprout breeding rewards
[sprouts]
	#the default chance for a sprout breeding reward to be given when not contained within the sprout breeding rewards data map (only applies to items within the roots:sprout_breeding_rewards tag)
	# Default: 10
	# Range: 1 ~ 100
	default_chance = 10

#Options for the Alertness charm
[alertness]
	#whether or not the Alertness charm should display a visual effect
	visual = true
	#the duration of the Alertness charm effect in ticks
	# Default: 200
	# Range: > 1
	duration = 200
	#whether or not the Alertness charm should play a sound when activated
	sound = true
	#whether or not entities should be filtered to those in the roots:alertness entity tag
	tag = false

[debug]
	#if true, will send messages for all reputation gains and losses
	debug_reputation = false
	#if true, will report in the message log whenever a Grove Action has been fired
	debug_grove_actions = false
	#if true, will print debug information about keybinds to the message log
	debug_keybinds = false
	#if true, will print debug information about server->client recipe syncs to the message log
	debug_jei = false

[ritual_conflict]
	#how rituals (heavy storms, protection) will be resolved on the server: [protection_priority=the protection ritual will always suppress the weather effects of heavy storms, storm_priority=the heavy storms ritual will always change the weather even with protection running, age_priority=the ritual started earliest will have priority]
	#Allowed Values: STORM_PRIORITY, PROTECTION_PRIORITY, AGE_PRIORITY
	ritual_resolution_type = "AGE_PRIORITY"

#Options for Grove Stones
[grove_stones]
	#the X and Z half value for the size of the Rank 1 Grove Stone aoe bounding box
	# Default: 3
	# Range: > 1
	rank_1_grove_bounds_zx = 3
	#the Y half value for the size of the Rank 1 Grove Stone aoe bounding box
	# Default: 3
	# Range: > 1
	rank_1_grove_bounds_y = 3
	#the X and Z half value for the size of the Rank 2 Grove Stone aoe bounding box
	# Default: 8
	# Range: > 1
	rank_2_grove_bounds_zx = 8
	#the Y half value for the size of the Rank 2 Grove Stone aoe bounding box
	# Default: 8
	# Range: > 1
	rank_2_grove_bounds_y = 8
	#the X and Z half value for the size of the Rank 3 Grove Stone aoe bounding box
	# Default: 15
	# Range: > 1
	rank_3_grove_bounds_zx = 15
	#the Y half value for the size of the Rank 3 Grove Stone aoe bounding box
	# Default: 15
	# Range: > 1
	rank_3_grove_bounds_y = 15
	#the X and Z half value for the size of the Rank 4 Grove Stone aoe bounding box
	# Default: 30
	# Range: > 1
	rank_4_grove_bounds_zx = 30
	#the Y half value for the size of the Rank 4 Grove Stone aoe bounding box
	# Default: 30
	# Range: > 1
	rank_4_grove_bounds_y = 30
	#the X half value for the size of the Grove Stone power range
	# Default: 30
	# Range: > 1
	grove_stone_power_range_x = 30
	#the Y half value for the size of the Grove Stone power range
	# Default: 30
	# Range: > 1
	grove_stone_power_range_y = 30
	#the Z half value for the size of the Grove Stone power range
	# Default: 30
	# Range: > 1
	grove_stone_power_range_z = 30

#Options for Growth Amplifiers
[growth_amplifier]
	#the Z half value for the size of the Growth Amplifier aoe bounding box
	# Default: 2
	# Range: > 1
	growth_amplifier_bounds_z = 2
	#the X half value for the size of the Growth Amplifier aoe bounding box
	# Default: 2
	# Range: > 1
	growth_amplifier_bounds_x = 2
	#the Y half value for the size of the Growth Amplifier aoe bounding box
	# Default: 2
	# Range: > 1
	growth_amplifier_bounds_y = 2
	#the number of ticks the Enchanted Turf will take to create a new grass block above it
	# Default: 100
	# Range: > 1
	enchanted_turf_ticks = 100

[grass_drops]
	#whether or not aubergine seeds should drop from grass
	drop_aubergine_seeds = true
	#whether or not wildroot should drop from grass
	drop_wildroot = true
	#whether or not grove spores should drop from grass
	drop_grove_spores = true

[fungal_transmuter]
	#the amount of power the Fungal Transmuter will consume per tick
	# Default: 1
	# Range: > 1
	fungal_transmuter_power_per_tick = 50
	#the maximum amount of power the Fungal Transmuter can store
	# Default: 5000
	# Range: > 1
	fungal_transmuter_max_stored_power = 5000

[elemental_soil]
	#whether or not elemental crops should have a chance to drop extra items when harvested
	elemental_crop_extra_drops = true
	#the chance for elemental crops to drop extra items when harvested, if enabled and a specific drop chance isn't already specified in the data map
	# Default: 0.1
	# Range: 0.0 ~ 1.0
	elemental_crop_extra_drops_chance = 0.1

#Configuration options relating to the mortar & pestle
[mortar]
	#the cooldown in ticks after using a pestle on a mortar, -1 for no cooldown
	# Default: 20
	# Range: > -1
	pestle_cooldown = 20
