[infinityCard]
	#The energy need to run the Infinity Card
	# Default: 4000
	# Range: > 0
	energyUsage = 4200

[dimensionCard]
	#The energy need to run the Dimension Card
	# Default: 8000
	# Range: > 0
	energyUsage = 9001
