!!dev.wuffs.squatgrow.config.SquatGrowConfig
ae2Multiplier: 2
allowAdventureTwerking: true
chance: 0.5
debug: false
enableAE2Accelerator: true
enableDirtToGrass: false
enableMysticalCrops: false
hoeTakesDamage: true
ignoreList: ['minecraft:grass_block', 'minecraft:grass', 'minecraft:tall_grass', 'minecraft:netherrack',
  'minecraft:warped_nylium', 'minecraft:crimson_nylium', '#mysticalagriculture:crops',
  'minecraft:moss_block']
randomTickMultiplier: 4
range: 3
requireHoe: true
requirements:
  durabilityDamage: 1
  enabled: true
  equipmentRequirement: {}
  heldItemRequirement: ['#ftb:non_silent_hoes']
  requiredEnchantment: ''
  requiredItemTakesDamage: false
sugarcaneMultiplier: 4
useWhitelist: false
