#General settings
[general]
	#Setting this to false disables the statue bat from spawning naturally (Default: true)
	statueBatSpawning = true
	#When enabled this will allow Ancient City loot to contain statues (Default: true)
	ancientCityLoot = true
	#The chance of a statue appearing in ancient City loot (Default: 0.1)
	# Default: 0.1
	# Range: 0.0 ~ 1.0
	ancientCityLootChance = 0.1
	#The amount of ticks before an upgraded statue becomes interact-able (Default: 200)
	# Default: 200
	# Range: > 1
	statueCooldown = 200
	#The minimum cooldown in ticks a statue can have after the speed has been subtracted (Default: 10)
	# Default: 10
	# Range: > 1
	statuesMinCooldown = 10
	#The amount of ticks subtracted from the statue cooldown per level of Speed applied (Default: 20)
	# Default: 20
	# Range: > 1
	statueSpeedUpgrade = 20

#Statue drop Settings
[drops]
	#The drop chance of statues when statue drops is true (Default: 0.01)
	# Default: 0.01
	# Range: 0.0 ~ 1.0
	statueDropChance = 0.01
	#Source of death that determines how the Statues drop (Default: "PLAYER") [player statue has it's own config option]
	#ALL = All sources
	#PLAYER = Player only
	#PLAYER_FAKEPLAYER = Players / Fake players only
	#Allowed Values: ALL, PLAYER, PLAYER_FAKEPLAYER
	statueKillSource = "PLAYER"

#Player Statue Settings
[player]
	#When true players will drop Player Statues when killed (Default: true)
	playerDropsStatue = true
	#Source of death that determines how the Player Statue drops (Default: "PLAYER") [player statue has it's own config option]
	#ALL = All sources
	#PLAYER = Player only
	#PLAYER_FAKEPLAYER = Players / Fake players only
	#Allowed Values: ALL, PLAYER, PLAYER_FAKEPLAYER
	playerDropsKillSource = "PLAYER"
	#The drop chance of player statues when playerDropsStatue is enabled (Default: 1.0)
	# Default: 1.0
	# Range: 0.0 ~ 1.0
	statueDropChance = 1.0
	#When true Statues will add a player compass (Default: true)
	playerCompass = true

#Info messages
[info_messages]
	#Adding lines / removing lines specifies what the informative statue can say
	info_messages = ["Statues is still in beta not all mobs have a statue yet", "Chickens are not royal, prove me wrong by placing the right statue on a royal looking block", "Undead stop burning in water, would a statue burn on a block that looks like water?", "Fun Fact: I was supposed to be a christmas special item, but plans got changed and now I am here", "Pigs love mud how will they react on a more sandy block", "Did you know chicken jockeys exist even in statues? go ahead try it out place a baby zombie statue on a chicken statue", "Huge thanks to Xisuma for helping create his statue", "Gone Fishing", "1-3 tall they seem, prickly is a bit mean, Give them a hat and see their true means", "Right click a player statue with a comparator to emit redstone when that player is online", "Right click a player statue with a compass to bound the compass to the last known location of the player", "A player and a creeper next to a pool of lave, throw in a shiny rock", "Rename a bee 'Trans Bee' to show support for trans people", "Rename a bee to a tropical name to find its name-sake", "Using a Statue Core on a player statue will make them grow, and will add more features to it", "The bat has returned, find them in caves near you, or in your local hellish dimension", "Check the pockets of your local wondering traders", "Looking for a player skin? Just rename the right statue"]

#Lucky players
[lucky_players]
	#Adding usernames will make these users have less luck with getting statues
	lucky_players = [""]

#Power Settings
[power_settings]
	#When true statues will require power to function when upgraded (Default: false)
	requiresPower = true
	#If statues should drain power over time (Default: true)
	powerDrain = true
	#The power used to generate an item (200)
	# Default: 200
	# Range: > 0
	itemPowerUsage = 200
	#The power used to kill a mob (500)
	# Default: 500
	# Range: > 0
	killPowerUsage = 500
	#The power used to summon a mob (500)
	# Default: 100
	# Range: > 0
	spawnPowerUsage = 100
	#The power used to despawn a mob (250)
	# Default: 250
	# Range: > 0
	despawnPowerUsage = 250
